# Generated by Django 4.2.2 on 2023-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_categorie_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issue_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
