# Generated by Django 4.2.2 on 2023-07-24 18:30

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_issue_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=inventory.models.NameField(blank=True, default='no name', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
