# Generated by Django 4.2.2 on 2023-07-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_qps_product_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='issue_to',
        ),
    ]
