# Generated by Django 4.2.2 on 2023-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_issue_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issue_stock',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
