# Generated by Django 4.2.2 on 2023-07-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_issue_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
