# Generated by Django 4.2.2 on 2023-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='r_quantity',
            field=models.IntegerField(blank=True, default='0', verbose_name='receipt quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qps',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', verbose_name='total quantity'),
        ),
    ]
