# Generated by Django 4.2.2 on 2023-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_r_quantity_alter_product_qps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='r_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
